POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Mazda",
  "model": "RX9",
  "year": 2002,
  "mileage": 1000,
  "lng": 42,
  "lat":42,
  "price": 37500
}

### Approve vehicle of user
PATCH  http://localhost:3000/reports/14
Content-Type: application/json

{
  "approved": true
}

### Get an estimate for the existing vehicle
GET http://localhost:3000/reports?make=Mazda&model=RX9&lng=40&lat=40&mileage=20000&year=2000