POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Mazda",
  "model": "RX9",
  "year": 2001,
  "mileage": 18000,
  "lng": 42,
  "lat":42,
  "price": 15000
}

### Approve vehicle of user
PATCH  http://localhost:3000/reports/4
Content-Type: application/json

{
  "approved": true
}

### Get an estimate for the existing vehicle
GET http://localhost:3000/reports?make=Toyota&model=Corolla&lng=0&lat=0&mileage=20000&year=1997